/*
File Name : common_audit_field_type_maintenance_20260720.sql
Purpose   : One-time hardcoded COMMON audit/code field type maintenance.
Scope     : 285 explicit columns across 48 tables.
Included  : program_id, status_code, menu_code, button_code, user_role_code,
            created_by, updated_by, deleted_by, client_ip, user_login_id, user_name.
Excluded  : cm_sequence (HOLD). Backup tables are excluded by inventory policy.
Safety    : No dynamic SQL. Original NULL, DEFAULT, COMMENT and column attributes are preserved.
DDL Note  : MariaDB DDL auto-commits. Execute only after a database backup/snapshot.
*/

SET NAMES utf8mb4;

SELECT 'BEFORE' AS verification_step, table_name, column_name, column_type
FROM information_schema.columns
WHERE table_schema = 'te_common'
  AND (table_name, column_name) IN
(
    ('cm_audit_policy', 'created_by'),
    ('cm_audit_policy', 'updated_by'),
    ('cm_audit_policy', 'deleted_by'),
    ('cm_audit_policy', 'program_id'),
    ('cm_audit_policy', 'client_ip'),
    ('cm_audit_policy', 'status_code'),
    ('cm_business_domain', 'created_by'),
    ('cm_business_domain', 'updated_by'),
    ('cm_business_domain', 'deleted_by'),
    ('cm_business_domain', 'program_id'),
    ('cm_business_domain', 'client_ip'),
    ('cm_business_domain', 'status_code'),
    ('cm_change_history', 'created_by'),
    ('cm_change_history', 'client_ip'),
    ('cm_change_history', 'program_id'),
    ('cm_change_history', 'status_code'),
    ('cm_code_inspection_result', 'created_by'),
    ('cm_code_inspection_result', 'updated_by'),
    ('cm_code_inspection_result', 'deleted_by'),
    ('cm_code_inspection_result', 'client_ip'),
    ('cm_code_inspection_result', 'program_id'),
    ('cm_code_inspection_result', 'status_code'),
    ('cm_common_code', 'status_code'),
    ('cm_common_code', 'created_by'),
    ('cm_common_code', 'updated_by'),
    ('cm_common_code', 'client_ip'),
    ('cm_common_code', 'deleted_by'),
    ('cm_common_code', 'program_id'),
    ('cm_common_code_group', 'status_code'),
    ('cm_common_code_group', 'created_by'),
    ('cm_common_code_group', 'updated_by'),
    ('cm_common_code_group', 'client_ip'),
    ('cm_common_code_group', 'deleted_by'),
    ('cm_common_code_group', 'program_id'),
    ('cm_consent_history', 'created_by'),
    ('cm_consent_history', 'updated_by'),
    ('cm_consent_history', 'deleted_by'),
    ('cm_consent_history', 'client_ip'),
    ('cm_consent_history', 'program_id'),
    ('cm_consent_history', 'status_code'),
    ('cm_country', 'status_code'),
    ('cm_country', 'created_by'),
    ('cm_country', 'updated_by'),
    ('cm_country', 'client_ip'),
    ('cm_country', 'deleted_by'),
    ('cm_country', 'program_id'),
    ('cm_data_classification', 'created_by'),
    ('cm_data_classification', 'updated_by'),
    ('cm_data_classification', 'deleted_by'),
    ('cm_data_classification', 'client_ip'),
    ('cm_data_classification', 'program_id'),
    ('cm_data_classification', 'status_code'),
    ('cm_data_lifecycle_index', 'status_code'),
    ('cm_data_lifecycle_index', 'created_by'),
    ('cm_data_lifecycle_index', 'updated_by'),
    ('cm_data_lifecycle_index', 'deleted_by'),
    ('cm_data_lifecycle_index', 'client_ip'),
    ('cm_data_lifecycle_index', 'program_id'),
    ('cm_data_type', 'created_by'),
    ('cm_data_type', 'updated_by'),
    ('cm_data_type', 'deleted_by'),
    ('cm_data_type', 'client_ip'),
    ('cm_data_type', 'program_id'),
    ('cm_data_type', 'status_code'),
    ('cm_language', 'status_code'),
    ('cm_language', 'created_by'),
    ('cm_language', 'updated_by'),
    ('cm_language', 'client_ip'),
    ('cm_language', 'deleted_by'),
    ('cm_language', 'program_id'),
    ('cm_legal_retention_policy', 'created_by'),
    ('cm_legal_retention_policy', 'updated_by'),
    ('cm_legal_retention_policy', 'deleted_by'),
    ('cm_legal_retention_policy', 'client_ip'),
    ('cm_legal_retention_policy', 'program_id'),
    ('cm_legal_retention_policy', 'status_code'),
    ('cm_locale', 'status_code'),
    ('cm_locale', 'created_by'),
    ('cm_locale', 'updated_by'),
    ('cm_locale', 'deleted_by'),
    ('cm_locale', 'client_ip'),
    ('cm_locale', 'program_id'),
    ('cm_login_history', 'client_ip'),
    ('cm_login_history', 'status_code'),
    ('cm_member', 'created_by'),
    ('cm_member', 'updated_by'),
    ('cm_member', 'client_ip'),
    ('cm_member', 'deleted_by'),
    ('cm_member', 'program_id'),
    ('cm_member', 'status_code'),
    ('cm_member_private', 'created_by'),
    ('cm_member_private', 'updated_by'),
    ('cm_member_private', 'client_ip'),
    ('cm_member_private', 'deleted_by'),
    ('cm_member_private', 'program_id'),
    ('cm_member_private', 'status_code'),
    ('cm_member_role', 'created_by'),
    ('cm_member_role', 'updated_by'),
    ('cm_member_role', 'client_ip'),
    ('cm_member_role', 'deleted_by'),
    ('cm_member_role', 'program_id'),
    ('cm_member_role', 'status_code'),
    ('cm_repository', 'status_code'),
    ('cm_repository', 'created_by'),
    ('cm_repository', 'updated_by'),
    ('cm_repository', 'client_ip'),
    ('cm_repository', 'deleted_by'),
    ('cm_repository', 'program_id'),
    ('cm_role', 'created_by'),
    ('cm_role', 'updated_by'),
    ('cm_role', 'client_ip'),
    ('cm_role', 'deleted_by'),
    ('cm_role', 'program_id'),
    ('cm_role', 'status_code'),
    ('cm_role_rule', 'created_by'),
    ('cm_role_rule', 'updated_by'),
    ('cm_role_rule', 'deleted_by'),
    ('cm_role_rule', 'program_id'),
    ('cm_role_rule', 'client_ip'),
    ('cm_sequence_definition', 'status_code'),
    ('cm_sequence_definition', 'created_by'),
    ('cm_sequence_definition', 'updated_by'),
    ('cm_sequence_definition', 'client_ip'),
    ('cm_sequence_definition', 'deleted_by'),
    ('cm_sequence_definition', 'program_id'),
    ('cm_sequence_format', 'created_by'),
    ('cm_sequence_format', 'updated_by'),
    ('cm_sequence_format', 'deleted_by'),
    ('cm_sequence_format', 'client_ip'),
    ('cm_sequence_format', 'program_id'),
    ('cm_sequence_format', 'status_code'),
    ('cm_sequence_format_definition', 'status_code'),
    ('cm_sequence_format_definition', 'created_by'),
    ('cm_sequence_format_definition', 'updated_by'),
    ('cm_sequence_format_definition', 'client_ip'),
    ('cm_sequence_format_definition', 'deleted_by'),
    ('cm_sequence_format_definition', 'program_id'),
    ('cm_sequence_policy', 'created_by'),
    ('cm_sequence_policy', 'updated_by'),
    ('cm_sequence_policy', 'deleted_by'),
    ('cm_sequence_policy', 'client_ip'),
    ('cm_sequence_policy', 'program_id'),
    ('cm_sequence_policy', 'status_code'),
    ('cm_sequence_policy_definition', 'status_code'),
    ('cm_sequence_policy_definition', 'created_by'),
    ('cm_sequence_policy_definition', 'updated_by'),
    ('cm_sequence_policy_definition', 'client_ip'),
    ('cm_sequence_policy_definition', 'deleted_by'),
    ('cm_sequence_policy_definition', 'program_id'),
    ('cm_sequence_rule', 'created_by'),
    ('cm_sequence_rule', 'updated_by'),
    ('cm_sequence_rule', 'deleted_by'),
    ('cm_sequence_rule', 'client_ip'),
    ('cm_sequence_rule', 'program_id'),
    ('cm_sequence_rule', 'status_code'),
    ('cm_storage_policy', 'created_by'),
    ('cm_storage_policy', 'updated_by'),
    ('cm_storage_policy', 'deleted_by'),
    ('cm_storage_policy', 'client_ip'),
    ('cm_storage_policy', 'program_id'),
    ('cm_storage_policy', 'status_code'),
    ('cm_storage_repository', 'created_by'),
    ('cm_storage_repository', 'updated_by'),
    ('cm_storage_repository', 'deleted_by'),
    ('cm_storage_repository', 'client_ip'),
    ('cm_storage_repository', 'program_id'),
    ('cm_storage_repository', 'status_code'),
    ('cm_verified_sql_query', 'created_by'),
    ('cm_verified_sql_query', 'updated_by'),
    ('cm_verified_sql_query', 'deleted_by'),
    ('cm_verified_sql_query', 'status_code'),
    ('cm_verified_sql_query', 'program_id'),
    ('cm_verified_sql_query', 'client_ip'),
    ('ev_evidence', 'status_code'),
    ('ev_evidence', 'created_by'),
    ('ev_evidence', 'updated_by'),
    ('ev_evidence', 'deleted_by'),
    ('ev_evidence', 'program_id'),
    ('ev_evidence', 'client_ip'),
    ('ev_evidence_reference', 'created_by'),
    ('ev_evidence_reference', 'updated_by'),
    ('ev_evidence_reference', 'deleted_by'),
    ('ev_evidence_reference', 'program_id'),
    ('ev_evidence_reference', 'client_ip'),
    ('ev_evidence_reference', 'status_code'),
    ('ev_evidence_version', 'created_by'),
    ('ev_evidence_version', 'updated_by'),
    ('ev_evidence_version', 'deleted_by'),
    ('ev_evidence_version', 'program_id'),
    ('ev_evidence_version', 'client_ip'),
    ('ev_evidence_version', 'status_code'),
    ('health_report', 'created_by'),
    ('health_report', 'updated_by'),
    ('health_report', 'deleted_by'),
    ('health_report', 'client_ip'),
    ('health_report', 'program_id'),
    ('health_report', 'status_code'),
    ('md_object', 'status_code'),
    ('md_object', 'created_by'),
    ('md_object', 'updated_by'),
    ('md_object', 'deleted_by'),
    ('md_object', 'client_ip'),
    ('md_object', 'program_id'),
    ('md_relation', 'status_code'),
    ('md_relation', 'created_by'),
    ('md_relation', 'updated_by'),
    ('md_relation', 'deleted_by'),
    ('md_relation', 'client_ip'),
    ('md_relation', 'program_id'),
    ('rl_rule', 'status_code'),
    ('rl_rule', 'created_by'),
    ('rl_rule', 'updated_by'),
    ('rl_rule', 'deleted_by'),
    ('rl_rule', 'program_id'),
    ('rl_rule', 'client_ip'),
    ('rl_rule_action', 'created_by'),
    ('rl_rule_action', 'updated_by'),
    ('rl_rule_action', 'deleted_by'),
    ('rl_rule_action', 'program_id'),
    ('rl_rule_action', 'client_ip'),
    ('rl_rule_action', 'status_code'),
    ('rl_rule_condition', 'created_by'),
    ('rl_rule_condition', 'updated_by'),
    ('rl_rule_condition', 'deleted_by'),
    ('rl_rule_condition', 'program_id'),
    ('rl_rule_condition', 'client_ip'),
    ('rl_rule_condition', 'status_code'),
    ('rl_rule_evidence', 'created_by'),
    ('rl_rule_evidence', 'updated_by'),
    ('rl_rule_evidence', 'deleted_by'),
    ('rl_rule_evidence', 'program_id'),
    ('rl_rule_evidence', 'client_ip'),
    ('rl_rule_evidence', 'status_code'),
    ('sp_policy_rule_candidate', 'created_by'),
    ('sp_policy_rule_candidate', 'updated_by'),
    ('sp_policy_rule_candidate', 'deleted_by'),
    ('sp_policy_rule_candidate', 'client_ip'),
    ('sp_policy_rule_candidate', 'program_id'),
    ('sp_policy_rule_keyword', 'created_by'),
    ('sp_policy_rule_keyword', 'updated_by'),
    ('sp_policy_rule_keyword', 'deleted_by'),
    ('sp_policy_rule_keyword', 'client_ip'),
    ('sp_policy_rule_keyword', 'program_id'),
    ('sql_guard_execution_log', 'menu_code'),
    ('sql_guard_execution_log', 'button_code'),
    ('sql_guard_execution_log', 'status_code'),
    ('sql_guard_verification_log', 'created_by'),
    ('sql_guard_verification_log', 'updated_by'),
    ('sql_guard_verification_log', 'deleted_by'),
    ('sql_guard_verification_log', 'client_ip'),
    ('sql_guard_verification_log', 'program_id'),
    ('sql_guard_verification_log', 'status_code'),
    ('system_menu', 'menu_code'),
    ('system_menu', 'created_by'),
    ('system_menu', 'updated_by'),
    ('system_menu', 'deleted_by'),
    ('system_menu', 'client_ip'),
    ('system_menu', 'program_id'),
    ('system_menu', 'status_code'),
    ('system_menu_button', 'button_code'),
    ('system_menu_button', 'menu_code'),
    ('system_menu_button', 'created_by'),
    ('system_menu_button', 'updated_by'),
    ('system_menu_button', 'deleted_by'),
    ('system_menu_button', 'client_ip'),
    ('system_menu_button', 'program_id'),
    ('system_menu_button', 'status_code'),
    ('system_menu_button_crud_permission', 'menu_code'),
    ('system_menu_button_crud_permission', 'button_code'),
    ('system_menu_button_crud_permission', 'user_role_code'),
    ('system_menu_button_crud_permission', 'created_by'),
    ('system_menu_button_crud_permission', 'updated_by'),
    ('system_menu_button_crud_permission', 'deleted_by'),
    ('system_menu_button_crud_permission', 'client_ip'),
    ('system_menu_button_crud_permission', 'program_id'),
    ('system_menu_button_crud_permission', 'status_code'),
    ('system_user', 'user_login_id'),
    ('system_user', 'user_name'),
    ('system_user', 'user_role_code'),
    ('system_user', 'created_by'),
    ('system_user', 'updated_by'),
    ('system_user', 'deleted_by'),
    ('system_user', 'client_ip'),
    ('system_user', 'program_id'),
    ('system_user', 'status_code')
)
ORDER BY table_name, ordinal_position;

/* Drop only Foreign Keys affected by menu_code/button_code type changes. */
ALTER TABLE `te_common`.`system_menu_button` DROP FOREIGN KEY `fk_system_menu_button_menu`;
ALTER TABLE `te_common`.`system_menu_button_crud_permission` DROP FOREIGN KEY `fk_button_permission_button`;
ALTER TABLE `te_common`.`system_menu_button_crud_permission` DROP FOREIGN KEY `fk_button_permission_menu`;

/* Explicit physical type maintenance. */
ALTER TABLE `te_common`.`cm_audit_policy`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_business_domain`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_change_history`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM' COMMENT '변경자',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL COMMENT '접속 IP',
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL COMMENT '프로그램 ID',
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_code_inspection_result`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_common_code`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_common_code_group`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_consent_history`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_country`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_data_classification`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_data_lifecycle_index`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL COMMENT '상태',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_data_type`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_language`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_legal_retention_policy`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_locale`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_login_history`
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_member`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_member_private`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_member_role`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_repository`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_role`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_role_rule`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL COMMENT '데이터 생성 사용자 또는 실행 주체',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL COMMENT '데이터 최종 수정 사용자 또는 실행 주체',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL COMMENT '데이터 삭제 처리 사용자 또는 실행 주체',
    MODIFY COLUMN `program_id` VARCHAR(99) NOT NULL COMMENT '실행 프로그램 식별자',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL COMMENT '실행 클라이언트 IP 주소';

ALTER TABLE `te_common`.`cm_sequence_definition`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_sequence_format`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_sequence_format_definition`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_sequence_policy`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_sequence_policy_definition`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`cm_sequence_rule`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_storage_policy`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_storage_repository`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`cm_verified_sql_query`
    MODIFY COLUMN `created_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL COMMENT '최종 수정자',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL COMMENT '논리 삭제 수행자',
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL COMMENT '실행 프로그램 ID',
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL COMMENT '실행 클라이언트 IP';

ALTER TABLE `te_common`.`ev_evidence`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE' COMMENT '상태 코드',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`ev_evidence_reference`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`ev_evidence_version`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`health_report`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`md_object`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`md_relation`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`rl_rule`
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE' COMMENT '상태 코드',
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`rl_rule_action`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`rl_rule_condition`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`rl_rule_evidence`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`sp_policy_rule_candidate`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`sp_policy_rule_keyword`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL;

ALTER TABLE `te_common`.`sql_guard_execution_log`
    MODIFY COLUMN `menu_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `button_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`sql_guard_verification_log`
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`system_menu`
    MODIFY COLUMN `menu_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`system_menu_button`
    MODIFY COLUMN `button_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `menu_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`system_menu_button_crud_permission`
    MODIFY COLUMN `menu_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `button_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `user_role_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `te_common`.`system_user`
    MODIFY COLUMN `user_login_id` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `user_name` VARCHAR(150) NOT NULL,
    MODIFY COLUMN `user_role_code` VARCHAR(99) NOT NULL,
    MODIFY COLUMN `created_by` VARCHAR(99) NOT NULL DEFAULT 'SYSTEM',
    MODIFY COLUMN `updated_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `deleted_by` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `client_ip` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `program_id` VARCHAR(99) DEFAULT NULL,
    MODIFY COLUMN `status_code` VARCHAR(99) NOT NULL DEFAULT 'ACTIVE';

/* Restore the original Foreign Keys exactly as defined. */
ALTER TABLE `te_common`.`system_menu_button` ADD CONSTRAINT `fk_system_menu_button_menu` FOREIGN KEY (`menu_code`) REFERENCES `system_menu` (`menu_code`);
ALTER TABLE `te_common`.`system_menu_button_crud_permission` ADD CONSTRAINT `fk_button_permission_button` FOREIGN KEY (`button_code`) REFERENCES `system_menu_button` (`button_code`);
ALTER TABLE `te_common`.`system_menu_button_crud_permission` ADD CONSTRAINT `fk_button_permission_menu` FOREIGN KEY (`menu_code`) REFERENCES `system_menu` (`menu_code`);

SELECT 'AFTER' AS verification_step, table_name, column_name, column_type
FROM information_schema.columns
WHERE table_schema = 'te_common'
  AND (table_name, column_name) IN
(
    ('cm_audit_policy', 'created_by'),
    ('cm_audit_policy', 'updated_by'),
    ('cm_audit_policy', 'deleted_by'),
    ('cm_audit_policy', 'program_id'),
    ('cm_audit_policy', 'client_ip'),
    ('cm_audit_policy', 'status_code'),
    ('cm_business_domain', 'created_by'),
    ('cm_business_domain', 'updated_by'),
    ('cm_business_domain', 'deleted_by'),
    ('cm_business_domain', 'program_id'),
    ('cm_business_domain', 'client_ip'),
    ('cm_business_domain', 'status_code'),
    ('cm_change_history', 'created_by'),
    ('cm_change_history', 'client_ip'),
    ('cm_change_history', 'program_id'),
    ('cm_change_history', 'status_code'),
    ('cm_code_inspection_result', 'created_by'),
    ('cm_code_inspection_result', 'updated_by'),
    ('cm_code_inspection_result', 'deleted_by'),
    ('cm_code_inspection_result', 'client_ip'),
    ('cm_code_inspection_result', 'program_id'),
    ('cm_code_inspection_result', 'status_code'),
    ('cm_common_code', 'status_code'),
    ('cm_common_code', 'created_by'),
    ('cm_common_code', 'updated_by'),
    ('cm_common_code', 'client_ip'),
    ('cm_common_code', 'deleted_by'),
    ('cm_common_code', 'program_id'),
    ('cm_common_code_group', 'status_code'),
    ('cm_common_code_group', 'created_by'),
    ('cm_common_code_group', 'updated_by'),
    ('cm_common_code_group', 'client_ip'),
    ('cm_common_code_group', 'deleted_by'),
    ('cm_common_code_group', 'program_id'),
    ('cm_consent_history', 'created_by'),
    ('cm_consent_history', 'updated_by'),
    ('cm_consent_history', 'deleted_by'),
    ('cm_consent_history', 'client_ip'),
    ('cm_consent_history', 'program_id'),
    ('cm_consent_history', 'status_code'),
    ('cm_country', 'status_code'),
    ('cm_country', 'created_by'),
    ('cm_country', 'updated_by'),
    ('cm_country', 'client_ip'),
    ('cm_country', 'deleted_by'),
    ('cm_country', 'program_id'),
    ('cm_data_classification', 'created_by'),
    ('cm_data_classification', 'updated_by'),
    ('cm_data_classification', 'deleted_by'),
    ('cm_data_classification', 'client_ip'),
    ('cm_data_classification', 'program_id'),
    ('cm_data_classification', 'status_code'),
    ('cm_data_lifecycle_index', 'status_code'),
    ('cm_data_lifecycle_index', 'created_by'),
    ('cm_data_lifecycle_index', 'updated_by'),
    ('cm_data_lifecycle_index', 'deleted_by'),
    ('cm_data_lifecycle_index', 'client_ip'),
    ('cm_data_lifecycle_index', 'program_id'),
    ('cm_data_type', 'created_by'),
    ('cm_data_type', 'updated_by'),
    ('cm_data_type', 'deleted_by'),
    ('cm_data_type', 'client_ip'),
    ('cm_data_type', 'program_id'),
    ('cm_data_type', 'status_code'),
    ('cm_language', 'status_code'),
    ('cm_language', 'created_by'),
    ('cm_language', 'updated_by'),
    ('cm_language', 'client_ip'),
    ('cm_language', 'deleted_by'),
    ('cm_language', 'program_id'),
    ('cm_legal_retention_policy', 'created_by'),
    ('cm_legal_retention_policy', 'updated_by'),
    ('cm_legal_retention_policy', 'deleted_by'),
    ('cm_legal_retention_policy', 'client_ip'),
    ('cm_legal_retention_policy', 'program_id'),
    ('cm_legal_retention_policy', 'status_code'),
    ('cm_locale', 'status_code'),
    ('cm_locale', 'created_by'),
    ('cm_locale', 'updated_by'),
    ('cm_locale', 'deleted_by'),
    ('cm_locale', 'client_ip'),
    ('cm_locale', 'program_id'),
    ('cm_login_history', 'client_ip'),
    ('cm_login_history', 'status_code'),
    ('cm_member', 'created_by'),
    ('cm_member', 'updated_by'),
    ('cm_member', 'client_ip'),
    ('cm_member', 'deleted_by'),
    ('cm_member', 'program_id'),
    ('cm_member', 'status_code'),
    ('cm_member_private', 'created_by'),
    ('cm_member_private', 'updated_by'),
    ('cm_member_private', 'client_ip'),
    ('cm_member_private', 'deleted_by'),
    ('cm_member_private', 'program_id'),
    ('cm_member_private', 'status_code'),
    ('cm_member_role', 'created_by'),
    ('cm_member_role', 'updated_by'),
    ('cm_member_role', 'client_ip'),
    ('cm_member_role', 'deleted_by'),
    ('cm_member_role', 'program_id'),
    ('cm_member_role', 'status_code'),
    ('cm_repository', 'status_code'),
    ('cm_repository', 'created_by'),
    ('cm_repository', 'updated_by'),
    ('cm_repository', 'client_ip'),
    ('cm_repository', 'deleted_by'),
    ('cm_repository', 'program_id'),
    ('cm_role', 'created_by'),
    ('cm_role', 'updated_by'),
    ('cm_role', 'client_ip'),
    ('cm_role', 'deleted_by'),
    ('cm_role', 'program_id'),
    ('cm_role', 'status_code'),
    ('cm_role_rule', 'created_by'),
    ('cm_role_rule', 'updated_by'),
    ('cm_role_rule', 'deleted_by'),
    ('cm_role_rule', 'program_id'),
    ('cm_role_rule', 'client_ip'),
    ('cm_sequence_definition', 'status_code'),
    ('cm_sequence_definition', 'created_by'),
    ('cm_sequence_definition', 'updated_by'),
    ('cm_sequence_definition', 'client_ip'),
    ('cm_sequence_definition', 'deleted_by'),
    ('cm_sequence_definition', 'program_id'),
    ('cm_sequence_format', 'created_by'),
    ('cm_sequence_format', 'updated_by'),
    ('cm_sequence_format', 'deleted_by'),
    ('cm_sequence_format', 'client_ip'),
    ('cm_sequence_format', 'program_id'),
    ('cm_sequence_format', 'status_code'),
    ('cm_sequence_format_definition', 'status_code'),
    ('cm_sequence_format_definition', 'created_by'),
    ('cm_sequence_format_definition', 'updated_by'),
    ('cm_sequence_format_definition', 'client_ip'),
    ('cm_sequence_format_definition', 'deleted_by'),
    ('cm_sequence_format_definition', 'program_id'),
    ('cm_sequence_policy', 'created_by'),
    ('cm_sequence_policy', 'updated_by'),
    ('cm_sequence_policy', 'deleted_by'),
    ('cm_sequence_policy', 'client_ip'),
    ('cm_sequence_policy', 'program_id'),
    ('cm_sequence_policy', 'status_code'),
    ('cm_sequence_policy_definition', 'status_code'),
    ('cm_sequence_policy_definition', 'created_by'),
    ('cm_sequence_policy_definition', 'updated_by'),
    ('cm_sequence_policy_definition', 'client_ip'),
    ('cm_sequence_policy_definition', 'deleted_by'),
    ('cm_sequence_policy_definition', 'program_id'),
    ('cm_sequence_rule', 'created_by'),
    ('cm_sequence_rule', 'updated_by'),
    ('cm_sequence_rule', 'deleted_by'),
    ('cm_sequence_rule', 'client_ip'),
    ('cm_sequence_rule', 'program_id'),
    ('cm_sequence_rule', 'status_code'),
    ('cm_storage_policy', 'created_by'),
    ('cm_storage_policy', 'updated_by'),
    ('cm_storage_policy', 'deleted_by'),
    ('cm_storage_policy', 'client_ip'),
    ('cm_storage_policy', 'program_id'),
    ('cm_storage_policy', 'status_code'),
    ('cm_storage_repository', 'created_by'),
    ('cm_storage_repository', 'updated_by'),
    ('cm_storage_repository', 'deleted_by'),
    ('cm_storage_repository', 'client_ip'),
    ('cm_storage_repository', 'program_id'),
    ('cm_storage_repository', 'status_code'),
    ('cm_verified_sql_query', 'created_by'),
    ('cm_verified_sql_query', 'updated_by'),
    ('cm_verified_sql_query', 'deleted_by'),
    ('cm_verified_sql_query', 'status_code'),
    ('cm_verified_sql_query', 'program_id'),
    ('cm_verified_sql_query', 'client_ip'),
    ('ev_evidence', 'status_code'),
    ('ev_evidence', 'created_by'),
    ('ev_evidence', 'updated_by'),
    ('ev_evidence', 'deleted_by'),
    ('ev_evidence', 'program_id'),
    ('ev_evidence', 'client_ip'),
    ('ev_evidence_reference', 'created_by'),
    ('ev_evidence_reference', 'updated_by'),
    ('ev_evidence_reference', 'deleted_by'),
    ('ev_evidence_reference', 'program_id'),
    ('ev_evidence_reference', 'client_ip'),
    ('ev_evidence_reference', 'status_code'),
    ('ev_evidence_version', 'created_by'),
    ('ev_evidence_version', 'updated_by'),
    ('ev_evidence_version', 'deleted_by'),
    ('ev_evidence_version', 'program_id'),
    ('ev_evidence_version', 'client_ip'),
    ('ev_evidence_version', 'status_code'),
    ('health_report', 'created_by'),
    ('health_report', 'updated_by'),
    ('health_report', 'deleted_by'),
    ('health_report', 'client_ip'),
    ('health_report', 'program_id'),
    ('health_report', 'status_code'),
    ('md_object', 'status_code'),
    ('md_object', 'created_by'),
    ('md_object', 'updated_by'),
    ('md_object', 'deleted_by'),
    ('md_object', 'client_ip'),
    ('md_object', 'program_id'),
    ('md_relation', 'status_code'),
    ('md_relation', 'created_by'),
    ('md_relation', 'updated_by'),
    ('md_relation', 'deleted_by'),
    ('md_relation', 'client_ip'),
    ('md_relation', 'program_id'),
    ('rl_rule', 'status_code'),
    ('rl_rule', 'created_by'),
    ('rl_rule', 'updated_by'),
    ('rl_rule', 'deleted_by'),
    ('rl_rule', 'program_id'),
    ('rl_rule', 'client_ip'),
    ('rl_rule_action', 'created_by'),
    ('rl_rule_action', 'updated_by'),
    ('rl_rule_action', 'deleted_by'),
    ('rl_rule_action', 'program_id'),
    ('rl_rule_action', 'client_ip'),
    ('rl_rule_action', 'status_code'),
    ('rl_rule_condition', 'created_by'),
    ('rl_rule_condition', 'updated_by'),
    ('rl_rule_condition', 'deleted_by'),
    ('rl_rule_condition', 'program_id'),
    ('rl_rule_condition', 'client_ip'),
    ('rl_rule_condition', 'status_code'),
    ('rl_rule_evidence', 'created_by'),
    ('rl_rule_evidence', 'updated_by'),
    ('rl_rule_evidence', 'deleted_by'),
    ('rl_rule_evidence', 'program_id'),
    ('rl_rule_evidence', 'client_ip'),
    ('rl_rule_evidence', 'status_code'),
    ('sp_policy_rule_candidate', 'created_by'),
    ('sp_policy_rule_candidate', 'updated_by'),
    ('sp_policy_rule_candidate', 'deleted_by'),
    ('sp_policy_rule_candidate', 'client_ip'),
    ('sp_policy_rule_candidate', 'program_id'),
    ('sp_policy_rule_keyword', 'created_by'),
    ('sp_policy_rule_keyword', 'updated_by'),
    ('sp_policy_rule_keyword', 'deleted_by'),
    ('sp_policy_rule_keyword', 'client_ip'),
    ('sp_policy_rule_keyword', 'program_id'),
    ('sql_guard_execution_log', 'menu_code'),
    ('sql_guard_execution_log', 'button_code'),
    ('sql_guard_execution_log', 'status_code'),
    ('sql_guard_verification_log', 'created_by'),
    ('sql_guard_verification_log', 'updated_by'),
    ('sql_guard_verification_log', 'deleted_by'),
    ('sql_guard_verification_log', 'client_ip'),
    ('sql_guard_verification_log', 'program_id'),
    ('sql_guard_verification_log', 'status_code'),
    ('system_menu', 'menu_code'),
    ('system_menu', 'created_by'),
    ('system_menu', 'updated_by'),
    ('system_menu', 'deleted_by'),
    ('system_menu', 'client_ip'),
    ('system_menu', 'program_id'),
    ('system_menu', 'status_code'),
    ('system_menu_button', 'button_code'),
    ('system_menu_button', 'menu_code'),
    ('system_menu_button', 'created_by'),
    ('system_menu_button', 'updated_by'),
    ('system_menu_button', 'deleted_by'),
    ('system_menu_button', 'client_ip'),
    ('system_menu_button', 'program_id'),
    ('system_menu_button', 'status_code'),
    ('system_menu_button_crud_permission', 'menu_code'),
    ('system_menu_button_crud_permission', 'button_code'),
    ('system_menu_button_crud_permission', 'user_role_code'),
    ('system_menu_button_crud_permission', 'created_by'),
    ('system_menu_button_crud_permission', 'updated_by'),
    ('system_menu_button_crud_permission', 'deleted_by'),
    ('system_menu_button_crud_permission', 'client_ip'),
    ('system_menu_button_crud_permission', 'program_id'),
    ('system_menu_button_crud_permission', 'status_code'),
    ('system_user', 'user_login_id'),
    ('system_user', 'user_name'),
    ('system_user', 'user_role_code'),
    ('system_user', 'created_by'),
    ('system_user', 'updated_by'),
    ('system_user', 'deleted_by'),
    ('system_user', 'client_ip'),
    ('system_user', 'program_id'),
    ('system_user', 'status_code')
)
ORDER BY table_name, ordinal_position;
