-- Backfill missing change history for Verified Query 00009 and 00010.
-- Records five MODIFY changes and five REDESIGN restores.
INSERT INTO te_common.cm_change_history
(
    change_history_id,
    target_database_name,
    target_table_name,
    target_record_id,
    action_type,
    change_story,
    created_by,
    created_dt,
    client_ip,
    program_id,
    status_code
)
VALUES
('CM_CO_CHANGE_HISTORY_20260804_00009_01', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_AC_ACTION', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_AC_ACTION의 DECISION을 REDESIGN에서 MODIFY로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00009', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00009_02', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_AT_AUDIT', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_AT_AUDIT의 DECISION을 REDESIGN에서 MODIFY로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00009', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00009_03', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION의 DECISION을 REDESIGN에서 MODIFY로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00009', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00009_04', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION_DETAIL', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION_DETAIL의 DECISION을 REDESIGN에서 MODIFY로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00009', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00009_05', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_FB_FEEDBACK', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_FB_FEEDBACK의 DECISION을 REDESIGN에서 MODIFY로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00009', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00010_01', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_AC_ACTION', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_AC_ACTION의 DECISION을 MODIFY에서 REDESIGN으로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00010', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00010_02', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_AT_AUDIT', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_AT_AUDIT의 DECISION을 MODIFY에서 REDESIGN으로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00010', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00010_03', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION의 DECISION을 MODIFY에서 REDESIGN으로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00010', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00010_04', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION_DETAIL', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_DC_DECISION_DETAIL의 DECISION을 MODIFY에서 REDESIGN으로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00010', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE'),
('CM_CO_CHANGE_HISTORY_20260804_00010_05', 'te_story_platform', 'sp_knowledge_hold', 'KWH_TABLE_TE_HEALTH_COMPANION_FB_FEEDBACK', 'UPDATE', 'sp_knowledge_hold KWH_TABLE_TE_HEALTH_COMPANION_FB_FEEDBACK의 DECISION을 MODIFY에서 REDESIGN으로 변경했다. VERIFIED_QUERY_ID=CM_CO_TE_COMMON_CM_VERIFIED_SQL_QUERY_20260804_00010', 'SYSTEM', CURRENT_TIMESTAMP, '127.0.0.1', 'CM_CHANGE_HISTORY_BACKFILL_20260804', 'ACTIVE');
